module.exports = {
  NULL_VALUE: '필요한 값이 없습니다.',
  INVALID_TOKEN: '유효하지 않은 token 입니다.',
  EMPTY_TOKEN: '토큰값이 존재하지 않습니다.',
  EXPIRED_TOKEN: '만료된 토큰입니다.',
  EMPTY_REFRESH_TOKEN: '재발급 토큰이 존재하지 않습니다.',
  CREATE_TOKEN: '토큰 발급 완료.',
  REFRESH_TOKEN: '토큰 재발급 완료.',
  NO_SELECT_AUTHORITY: '조회 권한 없음.',
  USER_SELECTED: '회원 조회 성공.',
  PRODUCT_INSERT_SUCCESS: '제품 등록 성공',
  EFFICACY_INSERT_SUCCESS: '효능 등록 성공',
  NUTRIENT_INSERT_SUCCESS: '성분 등록 성공',
  INSERT_FAILED: '등록 실패',
  PRODUCT_DOSE_INSERT_SUCCESS: '복용 등록 성공',
  PRODUCT_DOSE_INSERT_DUPLICATED: '이미 복용 등록되었습니다.',
  INTERNAL_SERVER_ERROR: '서버 내부 에러',
  SUCCESS: 'success',
  DUPLICATED: 'duplicated',
}
