module.exports = {
  NULL_VALUE: '필요한 값이 없습니다.',
  INVALID_TOKEN: '유효하지 않은 token 입니다.',
  EMPTY_TOKEN: '토큰값이 존재하지 않습니다.',
  EXPIRED_TOKEN: '만료된 토큰입니다.',
  EMPTY_REFRESH_TOKEN: '재발급 토큰이 존재하지 않습니다.',
  CREATE_TOKEN: '토큰 발급 완료.',
  REFRESH_TOKEN: '토큰 재발급 완료.',
  NO_SELECT_AUTHORITY: '조회 권한 없음.',
  USER_SELECTED: '회원 조회 성공.',
  PRODUCT_INSERT_SUCCESS: '제품 등록 성공',
  SIGN_UP_INSERT_SUCCESS: '회원가입 성공',
  SIGN_IN_SUCCESS: '로그인 성공',
  SIGN_IN_PASSWORD_ERROR: '비밀번호 오류',
  VALID_ID: '이용가능한 아이디',
  INVALID_ID: '중복되는 아이디',
  MODIFY_SUCCESS: '닉네임 수정 완료',
  MODIFY_FAILED: '닉네임 수정 실패',
  SURVEY_INFO_SUCCESS: '개인정보 설문조사 성공',
  SURVEY_INFO_FAILED: '개인정보 설문조사 실패',
  SURVEY_LIFECYCLE_SUCCESS: '라이프사이클 설문조사 성공',
  SURVEY_LIFECYCLE_FAILED: '라이프사이클 설문조사 실패',
  EFFICACY_INSERT_SUCCESS: '효능 등록 성공',
  NUTRIENT_INSERT_SUCCESS: '성분 등록 성공',
  INSERT_FAILED: '등록 실패',
  PRODUCT_DOSE_INSERT_SUCCESS: '복용 등록 성공',
  PRODUCT_DOSE_MODIFY_SUCCESS: '복용 수정 성공',
  PRODUCT_DOSE_DELETE_SUCCESS: '복용 취소 성공',
  PRODUCT_DOSE_DELETE_FAIL: '복용 취소 실패',
  PRODUCT_DOSE_INSERT_DUPLICATED: '이미 복용 등록되었습니다.',
  INTERNAL_SERVER_ERROR: '서버 내부 에러',
  SUCCESS: 'success',
  DUPLICATED: 'duplicated',
  EFFICACY_SELECTED: '효능 리스트 조회 성공',
  DB_ERROR: '데이터베이스 에러',
  USER_LIST_GET_SUCCESS: '유저 관리 리스트 가져오기 성공',
  USER_LIST_GET_FAIL: '유저 관리 리스트 가져오기 실패',
  SELECT_SUCCESS: '조회 성공',
  REMOVE_CHILD_USER_SUCCESS: 'child 사용자 삭제 성공',
  REMOVE_CHILD_USER_FAIL: 'child 사용자 삭제 실패',
  DOSE_PRODUCT_DELETE_SUCCESS: '복용 제품 삭제 성공',
  DOSE_PRODUCT_DELETE_FAIL: '복용 제품 삭제 실패',
  MY_CARE_FUNCTIONAL_NUTRIENTS_SUCCESS: '기능 성분 가져오기 성공',
  MY_CARE_FUNCTIONAL_NUTRIENTS_FAIL: '기능 성분 가져오기 실패',
  GET_NUTRIENT_INFO_SUCCESS: '특정 성분 정보 가져오기 성공',
  GET_PRODUCT_DETAIL_INFO_SUCCESS: '제품 상세 정보 가져오기 성공',
  SEARCH_SUCCESS: '검색 성공',
  SEARCH_DATA_EMPTY: '검색 결과가 없습니다.',
  GET_PRODUCT_DETAIL_EFFICACY_SUCCESS: '제품 디테일 효능 성공',

}
